### ISSUE TITLE
Not functioning -- possible mod conflict?

### ISSUE THREAD

**Issue by LegendOfCatBro** [viktor-ferenczi/se-camera-group#4]
- Make group
- Add to toolbar as "view"
- Pressing button views one camera
- Pressing the button again to cycle does nothing
- Same camera every time i back out and then view the cameras again

Many other plugins and mods are on the world, could be a conflict? Camera panning is also installed. It is 1:21 in the morning so I don't have time to do extensive testing and give a good bug report. Appears to pass the idiot check; all 4 cameras are fully welded, powered, turned on, and owned by me.

Game version 1.204.017 b0, on a peer to peer world with a friend.

**Comment by viktor-ferenczi** [comment]
Fixed in 1.1.3

**Comment by viktor-ferenczi** [comment]
If you don't get the update, then stop the game, delete the `whitelist.bin` in the `Bin64/Plugins` folder, then start it again.
